---
title: "Hackathon Project"
format: html
editor: visual

params:
  npi : "1194143776"
---

## Provider Recognition

```{r}
#| echo: false
#| warning: false 

#load packages----
library(tidyverse)
library(janitor)
library(dplyr)
library(gt)

#import & clean data

ptexp_sampledata <- read.csv("C:/Users/4477078/OneDrive - Moffitt Cancer Center/Hackathon/data.csv")

commentdata<-ptexp_sampledata[-c(2535,2536), ]%>% #remove extra lines of info
  clean_names()

commentdata$npi_num<-as.character(commentdata$npi_num)

save(commentdata,file="G:/Press Ganey II/Reports/Ad Hoc/DEEP DIVE/Key Driver Reports/data/commentdata.Rdata")

name_filter<-commentdata%>%
  filter(npi_num == params$npi)%>%
  distinct(resource_name)
```

#### `r name_filter` (NPI: `r params$npi`)

```{r}
#| echo: false
#| warning: false

#run for parameterized data
commentdata<-commentdata%>%
  filter(npi_num == params$npi)

#separate into first and last name
commentdata[c('last_nm', 'first_nm' )] <- str_split_fixed(commentdata$resource_name, ' ', 2)

last_nm <- str_to_title(commentdata$last_nm)
first_nm <- str_to_title(commentdata$first_nm)

#look for first or last name in comment, print if it's there
x <- commentdata$response

y <-str_replace_all(x, " ", "") #remove spaces in response text

commentdata$check1 <- grepl(last_nm,  y)
commentdata$check2 <- grepl(first_nm, y)

findata <- commentdata %>%
  filter(check1 == 'TRUE' | check2 == 'TRUE') %>%
  select(response) %>%
  rename('Exceptional Comments' = response) %>%
  gt() %>%
  cols_align(align="left",columns = everything())%>%
  tab_options(column_labels.background.color = 'dodgerblue4')%>%
  tab_style(style=cell_text(align="center"), 
            locations = cells_column_labels(columns = everything())
            )

findata
```
